Test report
Daniel2894/workshop-api-testing-js pull request #4
Opened 2018-05-23 18:43 UTC by Daniel2894

2018-05-23 18:46 UTC, Daniel2894 commented
Me falto la imagen del reporte, aquí está:
![mochawesome report](https://user-images.githubusercontent.com/11368361/40444702-9e6916d2-5e8f-11e8-979d-efcea7b7fcc6.PNG)

2018-05-23 21:01 UTC, sorregom requested changes
check again, you are pushing reports

2018-05-23 21:01 UTC, sorregom commented on report/ApiTesting.html
> +<html lang="en"><head><meta charSet="utf-8"/><meta http-equiv="X-UA-Compatible" content="IE=edge"/><meta name="viewport" content="width=device-width, initial-scale=1"/><title>Mochawesome Report</titl
EOF

2018-05-23 21:01 UTC, sorregom commented on report/ApiTesting.json
> +{
please check again you are pushing reports
you can use the rebase to make this change a single commit after deleting the report, then a git push -f to rewrite your branch to never have this on its commits

2018-05-24 20:32 UTC, sorregom approved these changes
LGTM

2018-05-24 20:39 UTC, merged